-- Run this script in your Supabase SQL Editor to enable the Wishlist feature

-- 1. Create the wishlist table
create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references public.products(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- 2. Enable Row Level Security (Security Policies)
alter table public.wishlist enable row level security;

-- 3. Create Access Policies
-- Allow users to view their own wishlist items
create policy "Users can view their own wishlist" 
  on public.wishlist for select using ( auth.uid() = user_id );

-- Allow users to add items to their wishlist
create policy "Users can insert into their own wishlist" 
  on public.wishlist for insert with check ( auth.uid() = user_id );

-- Allow users to remove items from their wishlist
create policy "Users can delete from their own wishlist" 
  on public.wishlist for delete using ( auth.uid() = user_id );
