-- ==========================================
-- 0. CLEANUP (Run this to reset tables)
-- WARNING: This will delete existing products and profiles!
-- ==========================================
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists products cascade;
drop table if exists profiles cascade;
drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Admin Upload" on storage.objects;
drop policy if exists "Admin Delete" on storage.objects;

-- ==========================================
-- 1. PROFILES (Users & Admins)
-- ==========================================
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text,
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table profiles enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone" 
  on profiles for select using ( true );

create policy "Users can insert their own profile" 
  on profiles for insert with check ( auth.uid() = id );

create policy "Users can update own profile" 
  on profiles for update using ( auth.uid() = id );

-- ==========================================
-- 2. PRODUCTS (Catalog)
-- ==========================================
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  image_url text not null,
  featured boolean default false,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table products enable row level security;

-- Policies
create policy "Products are viewable by everyone" 
  on products for select using ( true );

create policy "Admins can insert products" 
  on products for insert 
  with check ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can update products" 
  on products for update 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can delete products" 
  on products for delete 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

-- ==========================================
-- 3. ORDERS (Sales Tracking)
-- ==========================================
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id),
  total_amount numeric not null,
  status text default 'pending', -- pending, completed, cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table orders enable row level security;

-- Policies
create policy "Users can view their own orders" 
  on orders for select using ( auth.uid() = user_id );

create policy "Admins can view all orders" 
  on orders for select 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Users can create orders" 
  on orders for insert with check ( auth.uid() = user_id );

-- ==========================================
-- 4. ORDER ITEMS (Best Seller Analytics)
-- ==========================================
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id),
  quantity integer default 1,
  price_at_purchase numeric not null -- In case product price changes later
);

-- Enable RLS
alter table order_items enable row level security;

-- Policies
create policy "Users can view their own order items" 
  on order_items for select 
  using ( exists ( select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid() ) );

create policy "Admins can view all order items" 
  on order_items for select 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Users can insert order items" 
  on order_items for insert with check ( true ); 

-- ==========================================
-- 5. STORAGE BUCKETS & POLICIES
-- ==========================================

-- Create the 'products' bucket with constraints
-- Note: limit is in bytes. 5MB = 5 * 1024 * 1024 = 5242880
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'products', 
  'products', 
  true, 
  5242880, 
  ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/jpg']
) on conflict (id) do nothing;

-- Policy: Public Read Access (Everyone can see images)
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'products' );

-- Policy: Admin Upload Access (Only admins can upload)
create policy "Admin Upload"
  on storage.objects for insert
  with check ( 
    bucket_id = 'products' 
    and exists ( select 1 from public.profiles where id = auth.uid() and is_admin = true )
  );

-- Policy: Admin Delete Access
create policy "Admin Delete"
  on storage.objects for delete
  using ( 
    bucket_id = 'products' 
    and exists ( select 1 from public.profiles where id = auth.uid() and is_admin = true )
  );
