-- ==========================================
-- 0. CLEANUP (Run this to reset tables)
-- WARNING: This will delete existing products and profiles!
-- ==========================================
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists products cascade;
drop table if exists contact_messages cascade;
drop table if exists contact_threads cascade;
drop table if exists profiles cascade;
drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Admin Upload" on storage.objects;
drop policy if exists "Admin Delete" on storage.objects;
-- Cleanup functions if needed
drop function if exists delete_user_account();

-- ==========================================
-- 1. PROFILES (Users & Admins)
-- ==========================================
create table profiles (
  -- Make ID trigger a cascade delete when auth.users row is removed
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  username text,
  phone text,
  address text,
  is_admin boolean default false,
  is_super_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table profiles enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone" 
  on profiles for select using ( true );

create policy "Users can insert their own profile" 
  on profiles for insert with check ( auth.uid() = id );

create policy "Users can update own profile" 
  on profiles for update using ( auth.uid() = id );

create policy "Super Admins can update any profile" 
  on profiles for update 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_super_admin = true ) );

-- Promotes the first user to Super Admin and Admin
create or replace function public.handle_new_user()
returns trigger as $$
declare
  raw_full_name text;
  raw_first_name text;
  raw_last_name text;
  is_first_user boolean;
begin
  -- Check if this is the first user
  select count(*) = 0 into is_first_user from public.profiles;

  -- Get user metadata safely
  raw_full_name := new.raw_user_meta_data->>'full_name';

-- ==========================================
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text default 'General',
  price numeric not null,
  image_url text not null,
  featured boolean default false,
  description text,
  stock_status text default 'In Stock', -- 'In Stock', 'Out of Stock'
  stock_quantity integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table products enable row level security;

-- Policies
create policy "Products are viewable by everyone" 
  on products for select using ( true );

create policy "Admins can insert products" 
  on products for insert 
  with check ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can update products" 
  on products for update 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can delete products" 
  on products for delete 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

-- ==========================================
-- 3. ORDERS (Sales Tracking)
-- ==========================================
create table orders (
  id bigint generated by default as identity primary key,
  -- Cascade delete orders when user is deleted
  user_id uuid references profiles(id) on delete cascade,
  total_amount numeric not null,
  status text default 'pending', -- pending, processing, delivered, completed, cancelled
  delivery_address text,
  shipping_address text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table orders enable row level security;

-- Policies
create policy "Users can view their own orders" 
  on orders for select using ( auth.uid() = user_id );

create policy "Admins can view all orders" 
  on orders for select 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Users can create orders" 
  on orders for insert with check ( auth.uid() = user_id );

create policy "Admins can update orders"
  on orders for update
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

-- ==========================================
-- 4. ORDER ITEMS (Best Seller Analytics)
-- ==========================================
create table order_items (
  id bigint generated by default as identity primary key,
  -- Cascade delete items when order is deleted
  order_id bigint references orders(id) on delete cascade,
  product_id bigint references products(id), 
  quantity integer default 1,
  price_at_purchase numeric not null 
);

-- Enable RLS
alter table order_items enable row level security;

-- Policies
create policy "Users can view their own order items" 
  on order_items for select 
  using ( exists ( select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid() ) );

create policy "Admins can view all order items" 
  on order_items for select 
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Users can insert order items" 
  on order_items for insert with check ( true ); 

-- ==========================================
-- 5. STORAGE BUCKETS & POLICIES
-- ==========================================

-- Create the 'products' bucket with constraints
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'products', 
  'products', 
  true, 
  5242880, 
  ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/jpg']
) on conflict (id) do nothing;

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'products' );

create policy "Admin Upload"
  on storage.objects for insert
  with check ( 
    bucket_id = 'products' 
    and exists ( select 1 from public.profiles where id = auth.uid() and is_admin = true )
  );

create policy "Admin Delete"
  on storage.objects for delete
  using (
    bucket_id = 'products'
    and exists ( select 1 from public.profiles where id = auth.uid() and is_admin = true )
  );

-- ==========================================
-- 6. TRIGGERS (Auto-Profile Creation)
-- ==========================================

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
declare
  raw_full_name text;
  raw_first_name text;
  raw_last_name text;
begin
  -- Get user metadata safely
  raw_full_name := new.raw_user_meta_data->>'full_name';
  raw_first_name := new.raw_user_meta_data->>'first_name';
  raw_last_name := new.raw_user_meta_data->>'last_name';
  
  -- If first/last name not available, try to parse full_name or email
  if raw_first_name is null then
    if raw_full_name is not null then
       raw_first_name := split_part(raw_full_name, ' ', 1);
       raw_last_name := split_part(raw_full_name, ' ', 2);

    else
       raw_first_name := split_part(new.email, '@', 1);
    end if;
  end if;

  insert into public.profiles (id, email, username, is_admin, is_super_admin)
  values (
    new.id, 
    new.email, 
    coalesce(raw_full_name, raw_first_name || ' ' || coalesce(raw_last_name, ''), split_part(new.email, '@', 1)),
    is_first_user, -- Only first user becomes Admin automatically
    is_first_user  -- Only first user becomes Super Admin automatically
  );
  return new;
end;
$$ language plpgsql security definer;


create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

-- Trigger to call the function on new user creation
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create trigger profiles_set_updated_at
  before update on profiles
  for each row
  execute procedure public.set_updated_at();

create trigger products_set_updated_at
  before update on products
  for each row
  execute procedure public.set_updated_at();

-- ==========================================
-- 7. CONTACT MESSAGING (Threads + Replies)
-- ==========================================

create table contact_threads (
  id bigint generated by default as identity primary key,
  customer_id uuid references profiles(id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  subject text,
  status text not null default 'open', -- open, closed
  last_message_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table contact_messages (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references contact_threads(id) on delete cascade,
  sender_id uuid references profiles(id) on delete set null,
  sender_role text not null check (sender_role in ('customer', 'admin')),
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index idx_contact_threads_customer_id on contact_threads(customer_id);
create index idx_contact_threads_status on contact_threads(status);
create index idx_contact_threads_last_message_at on contact_threads(last_message_at desc);
create index idx_contact_messages_thread_id_created_at on contact_messages(thread_id, created_at);

alter table contact_threads enable row level security;
alter table contact_messages enable row level security;

create policy "Admins can read all threads"
  on contact_threads for select
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Customers can read own threads"
  on contact_threads for select
  using ( customer_id = auth.uid() );

create policy "Anyone can create contact thread"
  on contact_threads for insert
  with check ( true );

create policy "Admins can update threads"
  on contact_threads for update
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create policy "Admins can read all messages"
  on contact_messages for select
  using (
    exists ( select 1 from profiles where id = auth.uid() and is_admin = true )
    or exists (
      select 1
      from contact_threads ct
      where ct.id = contact_messages.thread_id
        and ct.customer_id = auth.uid()
    )
  );

create policy "Anyone can create customer message"
  on contact_messages for insert
  with check ( sender_role = 'customer' );

create policy "Admins can create admin message"
  on contact_messages for insert
  with check (
    sender_role = 'admin'
    and exists ( select 1 from profiles where id = auth.uid() and is_admin = true )
  );

create or replace function public.bump_contact_thread_last_message()
returns trigger
language plpgsql
as $$
begin
  update contact_threads
  set
    last_message_at = timezone('utc'::text, now()),
    updated_at = timezone('utc'::text, now())
  where id = new.thread_id;
  return new;
end;
$$;

create trigger contact_threads_set_updated_at
  before update on contact_threads
  for each row
  execute procedure public.set_updated_at();

create trigger contact_messages_bump_thread
  after insert on contact_messages
  for each row
  execute procedure public.bump_contact_thread_last_message();

alter publication supabase_realtime add table contact_threads;
alter publication supabase_realtime add table contact_messages;

-- ==========================================
-- 8. ACCOUNT MANAGEMENT
-- ==========================================

-- Function to allow users to delete their own account
-- This must be SECURITY DEFINER to allow users to delete their own auth record
create or replace function delete_user_account()
returns void
language plpgsql
security definer
as $$
begin
  -- Delete the user from auth.users table
  -- This will cascade to public.profiles due to the FK setup in this schema file
  delete from auth.users where id = auth.uid();
end;
$$;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION delete_user_account() TO authenticated;

-- ==========================================
-- 9. ADMIN MANAGEMENT
-- ==========================================

-- Function to add a new admin (with limit of 2 additional admins)
create or replace function add_admin(target_email text)
returns json
language plpgsql
security definer
as $tag$
declare
  target_id uuid;
  admin_count integer;
  current_user_super boolean;
begin
  -- Check if caller is Super Admin
  select is_super_admin into current_user_super from profiles where id = auth.uid();
  if not current_user_super then
    return json_build_object('success', false, 'message', 'Only Super Admins can add admins.');
  end if;

  -- Check limit (Total non-super admins)
  -- 'Real Admin' is Super Admin. '2 more admins' means regular admins.
  select count(*) into admin_count from profiles where is_admin = true and is_super_admin = false;
  
  if admin_count >= 2 then
    return json_build_object('success', false, 'message', 'Maximum limit of 2 additional admins reached.');
  end if;

  -- Find target user
  select id into target_id from profiles where email = target_email;
  
  if target_id is null then
    return json_build_object('success', false, 'message', 'User with this email not found.');
  end if;

  -- Update target to Admin
  update profiles set is_admin = true where id = target_id;
  
  return json_build_object('success', true, 'message', 'Admin added successfully.');
end;
$tag$;

-- Function to remove an admin
create or replace function remove_admin(target_id uuid)
returns json
language plpgsql
security definer
as $tag$
declare
  current_user_super boolean;
  target_super boolean;
begin
  -- Check if caller is Super Admin
  select is_super_admin into current_user_super from profiles where id = auth.uid();
  if not current_user_super then
    return json_build_object('success', false, 'message', 'Only Super Admins can remove admins.');
  end if;

  -- Check targeting self or another Super Admin
  select is_super_admin into target_super from profiles where id = target_id;
  
  if target_super then
    return json_build_object('success', false, 'message', 'Cannot remove Super Admin access.');
  end if;

  -- Demote target
  update profiles set is_admin = false where id = target_id;
  
  return json_build_object('success', true, 'message', 'Admin removed successfully.');
end;
$tag$;

-- Grant permissions
GRANT EXECUTE ON FUNCTION add_admin(text) TO authenticated;
GRANT EXECUTE ON FUNCTION remove_admin(uuid) TO authenticated;


-- ==========================================
-- 10. MIGRATIONS (Fix existing admins)
-- ==========================================
-- Ensure at least one super admin exists (Promote the first admin found if none exist)
-- This is critical if the schema is updated but data is preserved (e.g. via alter table, or just running in SQL editor)
do \$\$
declare
  admin_exists boolean;
  super_admin_exists boolean;
begin
  -- Check if any admin exists
  select count(*) > 0 into admin_exists from profiles where is_admin = true;
  
  -- Check if any super admin exists
  select count(*) > 0 into super_admin_exists from profiles where is_super_admin = true;
  
  -- If admins exist but NO super admin exists, promote the oldest admin
  if admin_exists and not super_admin_exists then
    update profiles 
    set is_super_admin = true 
    where id = (
      select id 
      from profiles 
      where is_admin = true 
      order by created_at asc 
      limit 1
    );
  end if;
end \$\$;


-- ==========================================
-- 11. WISHLIST
-- ==========================================

create table wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- Enable RLS
alter table wishlist enable row level security;

-- Policies
create policy "Users can view their own wishlist" 
  on wishlist for select 
  using ( auth.uid() = user_id );

create policy "Users can delete from their own wishlist" 
  on wishlist for delete 
  using ( auth.uid() = user_id );

create policy "Users can insert into their own wishlist" 
  on wishlist for insert 
  with check ( auth.uid() = user_id );

-- Trigger to enforce maximum of 5 items
create or replace function check_wishlist_limit()
returns trigger as $tag$
declare
  item_count integer;
begin
  select count(*) into item_count from wishlist where user_id = auth.uid();
  
  if item_count >= 5 then
    raise exception 'Wishlist limit reached. You can only add up to 5 items.';
  end if;
  
  return new;
end;
$tag$ language plpgsql;

create trigger enforce_wishlist_limit
  before insert on wishlist
  for each row
  execute procedure check_wishlist_limit();

-- ==========================================
-- 11. WISHLIST FEATURE
-- ==========================================

create table if not exists wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- Enable RLS
alter table wishlist enable row level security;

-- Policies (We use 'do' block to avoid errors if policy already exists)
do $$
begin
    if not exists (select 1 from pg_policies where policyname = 'Users can view their own wishlist') then
        create policy "Users can view their own wishlist" 
          on wishlist for select 
          using ( auth.uid() = user_id );
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Users can delete from their own wishlist') then
        create policy "Users can delete from their own wishlist" 
          on wishlist for delete 
          using ( auth.uid() = user_id );
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Users can insert into their own wishlist') then
        create policy "Users can insert into their own wishlist" 
          on wishlist for insert 
          with check ( auth.uid() = user_id );
    end if;
end $$;


-- Function to enforce maximum of 5 items
create or replace function check_wishlist_limit()
returns trigger as $$
declare
  item_count integer;
begin
  select count(*) into item_count from wishlist where user_id = auth.uid();
  
  -- If we already have 5, and we're trying to add another one, stop it.
  if item_count >= 5 then
    raise exception 'Wishlist limit reached. You can only add up to 5 items.';
  end if;
  
  return new;
end;
$$ language plpgsql;

-- Trigger
drop trigger if exists enforce_wishlist_limit on wishlist;
create trigger enforce_wishlist_limit
  before insert on wishlist
  for each row
  execute procedure check_wishlist_limit();
